//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auth_service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_permission
    {
        public int Id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<bool> canEdit { get; set; }
        public Nullable<bool> canView { get; set; }
        public Nullable<bool> canDownload { get; set; }
        public Nullable<bool> canAdd { get; set; }
        public Nullable<bool> canDelete { get; set; }
        public Nullable<bool> createFolder { get; set; }
        public Nullable<bool> canShare { get; set; }
        public Nullable<bool> canUnShare { get; set; }
    }
}
