//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auth_service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int userId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> userType { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> adminGroupUser { get; set; }
    }
}
